### ISSUE TITLE
1045-1110: Farms, pipes, streams and reforestation: Reasoning about structured parallel processes using types and hylomorphisms

### ISSUE THREAD

**Issue by GemmaG** [ocamllabs/icfp2016-blog#46]
David Castro: University of St. Andrews
Susmit Sarkar: University of St. Andrews
Kevin Hammond: University of St. Andrews

**Comment by yomimono** [comment]
Notes added in commit 498ecd17067cb21ac90e664b8e1b30c3c93f3767 .
